### ISSUE TITLE
sync-clipping from http source.

### ISSUE THREAD

**Issue by romesh92** [aecreations/sync-clippings#17]
Can we have a feature to sync clipping from URL which should checksum of existing file & file present at http source & if there is any difference.It should download new file.

Thanks

**Comment by aecreations** [comment]
Rejecting this enhancement request due to security concerns.

**Comment by romesh92** [comment]
Hi,My use case is if we have multiple users part of same team. And they would like to use same clippings & would like to sync them across team.Having functionality of sync from URL or HTTP source should help in that matter.

**Comment by aecreations** [comment]
The Sync Clippings FAQ describes how this can be done: https://aecreations.io/clippings/sync.php
