### ISSUE TITLE
Make a Linux/MacOS version

### ISSUE THREAD

**Issue by Thomashighbaugh** [aecreations/sync-clippings#9]
Your python script is already tooled for Linux and macOS, your makefile makes it clear you can write a bash script. 

I am assuming there is some other reason that neither mac nor Linux is supported, which if I knew what your rationale was and it was something I could help out dealing with, I am more than happy but until I hear it from the dev himself, I am hesistant to jump into a rabbit hole that you have already dove down into. 

Thanks again, love the extension in general. Really helpful.

**Comment by Thomashighbaugh** [comment]
Awesome thanks for that and what an excellent dev, really responsive in the best way.

### Keep On Rockin

**Comment by aecreations** [comment]
The second beta release is the most up-to-date test version: https://aecreations.blogspot.com/2021/11/sync-clippings-helper-12-beta-2-for.html
Check back at the blog for updates: https://aecreations.blogspot.com/

**Comment by Thomashighbaugh** [comment]
I just installed the sync-helper, having been putting it off because there is always millions of things I need to do at a given moment and it ended up pushed back (you know life is what it is) but it all worked seamlessly and out of the box for me. Highly impressed with the smoothness and thoroughness of your implementation of the helper in python, honestly this is great work and I am deeply appreciative of it. No need for any distro specific instructions or packages due to pip being available for me on Void Linux same as anyone using Red Hat, Ubuntu or Alpine in a Docker container which I really think was a smart way to approach the situation and letting me choose the local directory meant seamless integration with Dropbox which is also really nice. 

Great tool, great developer. 10/10

**Comment by aecreations** [comment]
Release candidate 1 of Sync Clippings Helper 1.2 is now available: https://aecreations.blogspot.com/2022/07/sync-clippings-helper-12-release.html

The official release will be announced on the blog.
